name: visio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: ^0.10.5+9
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LogoDark.png
    - assets/images/SquareLight.png
    - assets/images/SquareDark.png
    - assets/images/identificacao.automatica.png
    - assets/images/aplicacao.educacional.png
    - assets/images/gestaoeorganizacao.png
    - assets/images/interfaceegerenciamento.png
    - assets/images/registroerastreamento.png
    - assets/images/segurancaeautenticacao.png